import type { Metadata } from 'next'
import { Poppins, Outfit } from 'next/font/google'
import './globals.css'

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '400', '500', '600'],
  style: ['italic', 'normal']
})

export const outfit = Outfit({
  subsets: ['latin'],
  weight: ['100', '400', '500', '600'],
  style: ['normal']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  )
}
